apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  replicas: 2
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: wisecow
        ports:
        - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
      nodePort: 31182
